version: '3'

services: 
    client-1: 
        container_name: "dimutex_1"
        image: dimutex:latest
        build: 
            dockerfile: ./Dockerfile
        environment: 
            - NAME="Henning"
            - ID = "1"
            - PORT: 8080  
    client-2: 
        container_name: "dimutex_2"
        image: dimutex:latest
        build: 
            dockerfile: ./Dockerfile
        environment: 
            - NAME="Mikki"
            - ID = "2"
            - PORT:  8081   
    client-3: 
        container_name: "dimutex_3"
        image: dimutex:latest
        build: 
            dockerfile: ./Dockerfile
        environment: 
            - NAME="Jens"
            - ID = "3"   
            - PORT: 8082    
    client-4: 
        container_name: "dimutex_4"
        image: dimutex:latest
        build: 
            dockerfile: ./Dockerfile
        environment: 
            - NAME="Børge"        
            - ID = "4"
            - PORT: 8083  